### ISSUE TITLE
Invalid on the weapon wheel

### ISSUE THREAD

**Issue by Twisterzz** [rubbertoe98/vWeaponsToolkit#1]
![unknown](https://user-images.githubusercontent.com/46792601/131261377-e35f7a62-1f3c-42cc-8a82-17297f9e24a0.png)
When spawning the gun it recognizes that it exists by giving me a message saying "weapon added to inventory" etc however when I open my weapon wheel it shows as invalid which the picture above shows and doesn't pull anything out

**Comment by Twisterzz** [comment]
Update: issue turned out to be that I tried to give it a name which is already in use, make sure to use unique names which don't conflict with other things already in

**Comment by kiven7777777** [comment]
> ![未知](https://user-images.githubusercontent.com/46792601/131261377-e35f7a62-1f3c-42cc-8a82-17297f9e24a0.png) 生成枪时，它通过给我一条消息“武器已添加到库存”等来识别它的存在，但是当我打开我的武器轮时，它显示为无效，如上图所示，并且没有拉出任何东西

can you show me how to open it
