### ISSUE TITLE
Update version?

### ISSUE THREAD

**Issue by Acodingnoob1** [rubbertoe98/vWeaponsToolkit#18]
How to update 1.0.3 to add more templates from recent commits?

**Comment by ansljeremy** [comment]
You'll need to wait for v1.0.4 (or whatever is next) for the templates from the recent commits. Alternatively you could build it yourself.

**Comment by rubbertoe98** [comment]
Added in [v1.0.4](https://github.com/rubbertoe98/vWeaponsToolkit/releases/tag/v1.0.4)
