### ISSUE TITLE
Crashes on export - WEAPON_MACHETE

### ISSUE THREAD

**Issue by MLGDuck** [rubbertoe98/vWeaponsToolkit#29]
Hello guys I seem to have a problem with the machete template the app crashes everytime I try to export.
Am I the only one with this problem?

Thank you <3

**Comment by Wolfhill09** [comment]
Hello, I will take a look when I am avalible

**Comment by rubbertoe98** [comment]
Fixed, thank you for the report, was due to malformed xml templates.
